### ISSUE TITLE
About the benefits of NeuMesh over the extracted geometry from neural fields

### ISSUE THREAD

**Issue by 07hyx06** [zju3dv/NeuMesh#17]
Hi, thanks for the great work and code. 

I have a question about this work. To support texture editing or geometry editing, a naive solution is to train a NeuS on the captured multi-view images, extract the mesh from the NeuS, and perform UV unwrapping. This way, we can import the assets to a 3D CG software, e.g. Blender, and perform all kinds of geometry and texture editing shown in the NeuMesh paper. Does NeuMesh achieve better rendering quality than the naive solution, or has other benefits?

**Comment by chobao** [comment]
Hi, 07hyx06, Thanks for your interest in our work!

I think extracting textured mesh from NeuS and rendering it by the 3D CG software will induce less photo-realistic results. The main reason is that the mesh texture is poor and loses the view-dependent phenomenon. Though some NeRF products (e.g. Luma AI) have been working on extracting photo-realistic mesh from NeRF,  vanilla NeuS can not satisfy this demand.

A further discussion is also included in "Section C. Using neural implicit representation instead of traditional textured
mesh" with Figure K in our supplementary material.

Hope it will help you!

<img width="723" alt="image" src="https://github.com/zju3dv/NeuMesh/assets/53040496/0f9b0c83-c8f0-4462-9393-877948708001">
