### ISSUE TITLE
Deforming Mesh

### ISSUE THREAD

**Issue by rahul-goel** [zju3dv/NeuMesh#7]
Hi! I have a query about the deformation of meshes with the current inference-only codebase.

Since we have a scan63 mesh in the repository. If we deform it externally by keeping the vertex count same, does the trained set of weights account for the deformation provided the deformation is relatively small? Or do we need to do anything additional?

**Comment by ybbbbt** [comment]
Hi Rahul,

If I understand correctly, you want to know how the deformation on the mesh affects the rendering.
Since we store geometry and texture codes on mesh vertices, the deformation on the mesh scaffold would directly map to the rendering results. 
The additional step is, for each transformed vertex, we also compute a relative rotation of the surface normal and compensate the rotation according to its sign indicator, as we explained in the paper. 
As for the weights, we use inverse distance weighting to interpolate codes on 8 nearest vertices, which can be automatically adjusted when the vertex position changes.
